//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 21-04-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
    
#import "bloodGroup.h"

@implementation bloodGroup

-(id) initWithEnum:(NSString*)itemName value:(int) itemValue
{
    if(self = [super init])
    {
        self->name=itemName;
        self->value=itemValue;
    }
    return self;
}

-(NSString*) stringValue
{
    return name;
}
    
-(NSString*) description
{
    return name;
}

-(int) getValue
{
    return value;
}

-(BOOL) isEqualTo:(bloodGroup *)item
{
    return [name isEqualToString:item->name];
}
   
-(void) serialize:(DDXMLNode*)parent
{
    [parent setStringValue:name];
}
     
+(bloodGroup*) Apositive
{
    static bloodGroup* obj=nil;
    if(!obj)
    {
        obj=[[bloodGroup alloc] initWithEnum: @"Apositive" value: 0];
    }
    return obj;
} 
+(bloodGroup*) Bpositive
{
    static bloodGroup* obj=nil;
    if(!obj)
    {
        obj=[[bloodGroup alloc] initWithEnum: @"Bpositive" value: 1];
    }
    return obj;
} 
+(bloodGroup*) AB
{
    static bloodGroup* obj=nil;
    if(!obj)
    {
        obj=[[bloodGroup alloc] initWithEnum: @"AB" value: 2];
    }
    return obj;
} 
+(bloodGroup*) ZeroNegative
{
    static bloodGroup* obj=nil;
    if(!obj)
    {
        obj=[[bloodGroup alloc] initWithEnum: @"ZeroNegative" value: 3];
    }
    return obj;
} 
+(bloodGroup*) ZeroPositive
{
    static bloodGroup* obj=nil;
    if(!obj)
    {
        obj=[[bloodGroup alloc] initWithEnum: @"ZeroPositive" value: 4];
    }
    return obj;
} 
    
+ (bloodGroup *)createWithXml:(DDXMLNode *)node
{
    return [bloodGroup createWithString:[node stringValue]];
}
    
+ (bloodGroup *)createWithString:(NSString *)value
{
    if([value isEqualToString:@"Bpositive"])
    {
        return [bloodGroup Bpositive];
    }
    if([value isEqualToString:@"AB"])
    {
        return [bloodGroup AB];
    }
    if([value isEqualToString:@"ZeroNegative"])
    {
        return [bloodGroup ZeroNegative];
    }
    if([value isEqualToString:@"ZeroPositive"])
    {
        return [bloodGroup ZeroPositive];
    }
    return [bloodGroup Apositive];   
}
    

@end
