//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 23-04-2015
//
//---------------------------------------------------


#import "Helper.h"
#import "getPreparedPrescriptionsCountForPatientResponse.h"


@implementation getPreparedPrescriptionsCountForPatientResponse
@synthesize _return;

+ (getPreparedPrescriptionsCountForPatientResponse *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self._return =0;
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"return" index:0])
        {
            self._return = [[[Helper getNode:__node name:@"return" index:0] stringValue] intValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
    DDXMLElement* ___returnItemElement=[__request writeElement:@"return" URI:@"" parent:__parent];
    [___returnItemElement setStringValue: [NSString stringWithFormat:@"%i", self._return]];


}
@end
