//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 23-04-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class company;
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface item : NSObject <ISerializableObject>


@property (retain,nonatomic,getter=getATC) NSString* ATC;

@property (retain,nonatomic,getter=getBeschreibung) NSString* beschreibung;

@property (retain,nonatomic,getter=getCheckInDate) NSString* checkInDate;

@property (retain,nonatomic,getter=getExpiryDate) NSString* expiryDate;

@property (retain,nonatomic,getter=getGTIN) NSString* GTIN;

@property (retain,nonatomic,getter=getLot) NSString* lot;

@property (retain,nonatomic,getter=getMenge) NSString* menge;

@property (retain,nonatomic,getter=getName) NSString* name;

@property (retain,nonatomic,getter=getProducer) company* producer;

@property (retain,nonatomic,getter=getSerial) NSString* serial;

@property (retain,nonatomic,getter=getZusatz) NSString* zusatz;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(item*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end