//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 16-04-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
#import "DDXMLElement.h"


@interface medicationState : NSObject
{
    int value;
    NSString* name;
}

+(medicationState*) createWithXml:(DDXMLNode*)node;
+(medicationState *)createWithString:(NSString *)value;
-(NSString*) stringValue;
-(NSString*) description;
-(int)getValue;
-(BOOL)isEqualTo:(medicationState *)item;
-(void) serialize:(DDXMLNode*)parent;
        
+(medicationState *) open;    
+(medicationState *) prepared;    
+(medicationState *) controlled;    
+(medicationState *) served;    
@end