//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 21-04-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
    
#import "medicationState.h"

@implementation medicationState

-(id) initWithEnum:(NSString*)itemName value:(int) itemValue
{
    if(self = [super init])
    {
        self->name=itemName;
        self->value=itemValue;
    }
    return self;
}

-(NSString*) stringValue
{
    return name;
}
    
-(NSString*) description
{
    return name;
}

-(int) getValue
{
    return value;
}

-(BOOL) isEqualTo:(medicationState *)item
{
    return [name isEqualToString:item->name];
}
   
-(void) serialize:(DDXMLNode*)parent
{
    [parent setStringValue:name];
}
     
+(medicationState*) open
{
    static medicationState* obj=nil;
    if(!obj)
    {
        obj=[[medicationState alloc] initWithEnum: @"open" value: 0];
    }
    return obj;
} 
+(medicationState*) prepared
{
    static medicationState* obj=nil;
    if(!obj)
    {
        obj=[[medicationState alloc] initWithEnum: @"prepared" value: 1];
    }
    return obj;
} 
+(medicationState*) controlled
{
    static medicationState* obj=nil;
    if(!obj)
    {
        obj=[[medicationState alloc] initWithEnum: @"controlled" value: 2];
    }
    return obj;
} 
+(medicationState*) served
{
    static medicationState* obj=nil;
    if(!obj)
    {
        obj=[[medicationState alloc] initWithEnum: @"served" value: 3];
    }
    return obj;
} 
    
+ (medicationState *)createWithXml:(DDXMLNode *)node
{
    return [medicationState createWithString:[node stringValue]];
}
    
+ (medicationState *)createWithString:(NSString *)value
{
    if([value isEqualToString:@"prepared"])
    {
        return [medicationState prepared];
    }
    if([value isEqualToString:@"controlled"])
    {
        return [medicationState controlled];
    }
    if([value isEqualToString:@"served"])
    {
        return [medicationState served];
    }
    return [medicationState open];   
}
    

@end
