//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 10-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "NIVRequestResultHandler.h"
#import "DDXML.h"



@interface NIVcompany : NSObject <NIVISerializableObject>


@property (retain,nonatomic,getter=getAbteilung) NSString* abteilung;

@property (retain,nonatomic,getter=getGLN) NSString* GLN;

@property (retain,nonatomic,getter=getName) NSString* name;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(NIVRequestResultHandler*) __request;
+(NIVcompany*) createWithXml:(DDXMLElement*)__node __request:(NIVRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(NIVRequestResultHandler*) __request;
@end