//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 10-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class NIVcompany;
#import "NIVRequestResultHandler.h"
#import "DDXML.h"



@interface NIVitem : NSObject <NIVISerializableObject>


@property (retain,nonatomic,getter=getATC) NSString* ATC;

@property (retain,nonatomic,getter=getBeschreibung) NSString* beschreibung;

@property (retain,nonatomic,getter=getCheckInDate) NSString* checkInDate;

@property (retain,nonatomic,getter=getExpiryDate) NSString* expiryDate;

@property (retain,nonatomic,getter=getGTIN) NSString* GTIN;

@property (retain,nonatomic,getter=getLot) NSString* lot;

@property (retain,nonatomic,getter=getMenge) NSString* menge;

@property (retain,nonatomic,getter=getName) NSString* name;

@property (retain,nonatomic,getter=getProducer) NIVcompany* producer;

@property (retain,nonatomic,getter=getSerial) NSString* serial;

@property (retain,nonatomic,getter=getZusatz) NSString* zusatz;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(NIVRequestResultHandler*) __request;
+(NIVitem*) createWithXml:(DDXMLElement*)__node __request:(NIVRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(NIVRequestResultHandler*) __request;
@end