//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 10-03-2015
//
//---------------------------------------------------


#import "NIVposition.h"
#import "NIVHelper.h"
#import "NIVorder.h"


@implementation NIVorder
@synthesize name;
@synthesize ordered;
@synthesize positions;

+ (NIVorder *)createWithXml:(DDXMLElement *)__node __request:(NIVRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.positions =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(NIVRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([NIVHelper hasValue:__node name:@"name" index:0])
        {
            self.name = [[NIVHelper getNode:__node name:@"name" index:0] stringValue];
        }
        if([NIVHelper hasValue:__node name:@"ordered" index:0])
        {
            self.ordered = [[[NIVHelper getNode:__node name:@"ordered" index:0] stringValue] boolValue];
        }
        if([NIVHelper hasValue:__node name:@"positions"])
        {
            NSArray* __items=[__node elementsForName:@"positions"];
            for (DDXMLElement* __item in __items) {
                [self.positions addObject:(NIVposition*)[__request createObject:__item type:[NIVposition class]]];
            }
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(NIVRequestResultHandler*) __request
{

             
    DDXMLElement* __nameItemElement=[__request writeElement:name type:[NSString class] name:@"name" URI:@"" parent:__parent skipNullProperty:YES];
    if(__nameItemElement!=nil)
    {
        [__nameItemElement setStringValue:self.name];
    }
             
    DDXMLElement* __orderedItemElement=[__request writeElement:@"ordered" URI:@"" parent:__parent];
    [__orderedItemElement setStringValue:[NIVHelper toBoolStringFromBool:self.ordered]];
             
    if(self.positions!=nil)
    {
        for (NIVposition* __item in self.positions) {
            DDXMLElement* __positionsItemElement=[__request writeElement:positions type:[NIVposition class] name:@"positions" URI:@"" parent:__parent skipNullProperty:NO];
            if(__positionsItemElement!=nil)
            {
                [__item serialize:__positionsItemElement __request: __request];
            }
        }
    }


}
@end
