//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 10-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class NIVposition;
#import "NIVRequestResultHandler.h"
#import "DDXML.h"



@interface NIVorder : NSObject <NIVISerializableObject>


@property (retain,nonatomic,getter=getName) NSString* name;

@property (nonatomic,getter=getOrdered) BOOL ordered;

@property (retain,nonatomic,getter=getPositions) NSMutableArray* positions;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(NIVRequestResultHandler*) __request;
+(NIVorder*) createWithXml:(DDXMLElement*)__node __request:(NIVRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(NIVRequestResultHandler*) __request;
@end