//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 10-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "NIVRequestResultHandler.h"
#import "DDXML.h"



@interface NIVposition : NSObject <NIVISerializableObject>


@property (retain,nonatomic,getter=getDescription) NSString* description;

@property (retain,nonatomic,getter=getGtin) NSString* gtin;

@property (nonatomic,getter=getQuantity) int quantity;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(NIVRequestResultHandler*) __request;
+(NIVposition*) createWithXml:(DDXMLElement*)__node __request:(NIVRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(NIVRequestResultHandler*) __request;
@end