//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 10-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class NIVitem;
#import "NIVRequestResultHandler.h"
#import "DDXML.h"



@interface NIVwebServiceResult : NSObject <NIVISerializableObject>


@property (retain,nonatomic,getter=getItems) NSMutableArray* items;

@property (nonatomic,getter=getResult) BOOL result;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(NIVRequestResultHandler*) __request;
+(NIVwebServiceResult*) createWithXml:(DDXMLElement*)__node __request:(NIVRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(NIVRequestResultHandler*) __request;
@end