//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 16-04-2015
//
//---------------------------------------------------


#import "position.h"
#import "Helper.h"
#import "order.h"


@implementation order
@synthesize name;
@synthesize ordered;
@synthesize positions;

+ (order *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.positions =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"name" index:0])
        {
            self.name = [[Helper getNode:__node name:@"name" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"ordered" index:0])
        {
            self.ordered = [[[Helper getNode:__node name:@"ordered" index:0] stringValue] boolValue];
        }
        if([Helper hasValue:__node name:@"positions"])
        {
            NSArray* __items=[__node elementsForName:@"positions"];
            for (DDXMLElement* __item in __items) {
                [self.positions addObject:(position*)[__request createObject:__item type:[position class]]];
            }
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
    DDXMLElement* __nameItemElement=[__request writeElement:name type:[NSString class] name:@"name" URI:@"" parent:__parent skipNullProperty:YES];
    if(__nameItemElement!=nil)
    {
        [__nameItemElement setStringValue:self.name];
    }
             
    DDXMLElement* __orderedItemElement=[__request writeElement:@"ordered" URI:@"" parent:__parent];
    [__orderedItemElement setStringValue:[Helper toBoolStringFromBool:self.ordered]];
             
    if(self.positions!=nil)
    {
        for (position* __item in self.positions) {
            DDXMLElement* __positionsItemElement=[__request writeElement:positions type:[position class] name:@"positions" URI:@"" parent:__parent skipNullProperty:NO];
            if(__positionsItemElement!=nil)
            {
                [__item serialize:__positionsItemElement __request: __request];
            }
        }
    }


}
@end
