//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 14-04-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class position;
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface order : NSObject <ISerializableObject>


@property (retain,nonatomic,getter=getName) NSString* name;

@property (nonatomic,getter=getOrdered) BOOL ordered;

@property (retain,nonatomic,getter=getPositions) NSMutableArray* positions;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(order*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end