//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 14-04-2015
//
//---------------------------------------------------


#import "Helper.h"
#import "position.h"


@implementation position
@synthesize description;
@synthesize gtin;
@synthesize quantity;

+ (position *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.quantity =0;
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"description" index:0])
        {
            self.description = [[Helper getNode:__node name:@"description" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"gtin" index:0])
        {
            self.gtin = [[Helper getNode:__node name:@"gtin" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"quantity" index:0])
        {
            self.quantity = [[[Helper getNode:__node name:@"quantity" index:0] stringValue] intValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
    DDXMLElement* __descriptionItemElement=[__request writeElement:description type:[NSString class] name:@"description" URI:@"" parent:__parent skipNullProperty:YES];
    if(__descriptionItemElement!=nil)
    {
        [__descriptionItemElement setStringValue:self.description];
    }
             
    DDXMLElement* __gtinItemElement=[__request writeElement:gtin type:[NSString class] name:@"gtin" URI:@"" parent:__parent skipNullProperty:YES];
    if(__gtinItemElement!=nil)
    {
        [__gtinItemElement setStringValue:self.gtin];
    }
             
    DDXMLElement* __quantityItemElement=[__request writeElement:@"quantity" URI:@"" parent:__parent];
    [__quantityItemElement setStringValue: [NSString stringWithFormat:@"%i", self.quantity]];


}
@end
