//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 16-04-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
#import "DDXMLElement.h"


@interface prescriptionState : NSObject
{
    int value;
    NSString* name;
}

+(prescriptionState*) createWithXml:(DDXMLNode*)node;
+(prescriptionState *)createWithString:(NSString *)value;
-(NSString*) stringValue;
-(NSString*) description;
-(int)getValue;
-(BOOL)isEqualTo:(prescriptionState *)item;
-(void) serialize:(DDXMLNode*)parent;
        
+(prescriptionState *) open;    
+(prescriptionState *) paused;    
+(prescriptionState *) stopped;    
+(prescriptionState *) doseChanged;    
@end