//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 23-04-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class item;
@class position;
@class shipment;
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface production : NSObject <ISerializableObject>


@property (retain,nonatomic,getter=getItems) NSMutableArray* items;

@property (retain,nonatomic,getter=getPositions) NSMutableArray* positions;

@property (retain,nonatomic,getter=getShipment) shipment* shipment;

@property (nonatomic,getter=getSuccess) BOOL success;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(production*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end