//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 21-04-2015
//
//---------------------------------------------------


#import "Helper.h"
#import "quantity.h"


@implementation quantity
@synthesize description;
@synthesize gtin;
@synthesize minQuantity;
@synthesize optQuantity;

+ (quantity *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.minQuantity =0;
        self.optQuantity =0;
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"description" index:0])
        {
            self.description = [[Helper getNode:__node name:@"description" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"gtin" index:0])
        {
            self.gtin = [[Helper getNode:__node name:@"gtin" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"minQuantity" index:0])
        {
            self.minQuantity = [[[Helper getNode:__node name:@"minQuantity" index:0] stringValue] intValue];
        }
        if([Helper hasValue:__node name:@"optQuantity" index:0])
        {
            self.optQuantity = [[[Helper getNode:__node name:@"optQuantity" index:0] stringValue] intValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
    DDXMLElement* __descriptionItemElement=[__request writeElement:description type:[NSString class] name:@"description" URI:@"" parent:__parent skipNullProperty:YES];
    if(__descriptionItemElement!=nil)
    {
        [__descriptionItemElement setStringValue:self.description];
    }
             
    DDXMLElement* __gtinItemElement=[__request writeElement:gtin type:[NSString class] name:@"gtin" URI:@"" parent:__parent skipNullProperty:YES];
    if(__gtinItemElement!=nil)
    {
        [__gtinItemElement setStringValue:self.gtin];
    }
             
    DDXMLElement* __minQuantityItemElement=[__request writeElement:@"minQuantity" URI:@"" parent:__parent];
    [__minQuantityItemElement setStringValue: [NSString stringWithFormat:@"%i", self.minQuantity]];
             
    DDXMLElement* __optQuantityItemElement=[__request writeElement:@"optQuantity" URI:@"" parent:__parent];
    [__optQuantityItemElement setStringValue: [NSString stringWithFormat:@"%i", self.optQuantity]];


}
@end
