//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 23-04-2015
//
//---------------------------------------------------


#import "order.h"
#import "Helper.h"
#import "setOrder.h"


@implementation setOrder
@synthesize arg0;
@synthesize arg1;
@synthesize arg2;

+ (setOrder *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"arg0" index:0])
        {
            self.arg0 = (order*)[__request createObject:[Helper getNode:__node name:@"arg0" index:0] type:[order class]];
        }
        if([Helper hasValue:__node name:@"arg1" index:0])
        {
            self.arg1 = [[Helper getNode:__node name:@"arg1" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"arg2" index:0])
        {
            self.arg2 = [[Helper getNode:__node name:@"arg2" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
    DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[order class] name:@"arg0" URI:@"" parent:__parent skipNullProperty:YES];
    if(__arg0ItemElement!=nil)
    {
        [self.arg0 serialize:__arg0ItemElement __request: __request];
    }
             
    DDXMLElement* __arg1ItemElement=[__request writeElement:arg1 type:[NSString class] name:@"arg1" URI:@"" parent:__parent skipNullProperty:YES];
    if(__arg1ItemElement!=nil)
    {
        [__arg1ItemElement setStringValue:self.arg1];
    }
             
    DDXMLElement* __arg2ItemElement=[__request writeElement:arg2 type:[NSString class] name:@"arg2" URI:@"" parent:__parent skipNullProperty:YES];
    if(__arg2ItemElement!=nil)
    {
        [__arg2ItemElement setStringValue:self.arg2];
    }


}
@end
