//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 14-04-2015
//
//---------------------------------------------------


#import "Helper.h"
#import "shipment.h"


@implementation shipment
@synthesize descDestination;
@synthesize descOrigin;
@synthesize glnDestination;
@synthesize glnOrigin;
@synthesize gsin;
@synthesize orderNr;
@synthesize sscc;

+ (shipment *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"descDestination" index:0])
        {
            self.descDestination = [[Helper getNode:__node name:@"descDestination" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"descOrigin" index:0])
        {
            self.descOrigin = [[Helper getNode:__node name:@"descOrigin" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"glnDestination" index:0])
        {
            self.glnDestination = [[Helper getNode:__node name:@"glnDestination" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"glnOrigin" index:0])
        {
            self.glnOrigin = [[Helper getNode:__node name:@"glnOrigin" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"gsin" index:0])
        {
            self.gsin = [[Helper getNode:__node name:@"gsin" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"orderNr" index:0])
        {
            self.orderNr = [[Helper getNode:__node name:@"orderNr" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"sscc" index:0])
        {
            self.sscc = [[Helper getNode:__node name:@"sscc" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
    DDXMLElement* __descDestinationItemElement=[__request writeElement:descDestination type:[NSString class] name:@"descDestination" URI:@"" parent:__parent skipNullProperty:YES];
    if(__descDestinationItemElement!=nil)
    {
        [__descDestinationItemElement setStringValue:self.descDestination];
    }
             
    DDXMLElement* __descOriginItemElement=[__request writeElement:descOrigin type:[NSString class] name:@"descOrigin" URI:@"" parent:__parent skipNullProperty:YES];
    if(__descOriginItemElement!=nil)
    {
        [__descOriginItemElement setStringValue:self.descOrigin];
    }
             
    DDXMLElement* __glnDestinationItemElement=[__request writeElement:glnDestination type:[NSString class] name:@"glnDestination" URI:@"" parent:__parent skipNullProperty:YES];
    if(__glnDestinationItemElement!=nil)
    {
        [__glnDestinationItemElement setStringValue:self.glnDestination];
    }
             
    DDXMLElement* __glnOriginItemElement=[__request writeElement:glnOrigin type:[NSString class] name:@"glnOrigin" URI:@"" parent:__parent skipNullProperty:YES];
    if(__glnOriginItemElement!=nil)
    {
        [__glnOriginItemElement setStringValue:self.glnOrigin];
    }
             
    DDXMLElement* __gsinItemElement=[__request writeElement:gsin type:[NSString class] name:@"gsin" URI:@"" parent:__parent skipNullProperty:YES];
    if(__gsinItemElement!=nil)
    {
        [__gsinItemElement setStringValue:self.gsin];
    }
             
    DDXMLElement* __orderNrItemElement=[__request writeElement:orderNr type:[NSString class] name:@"orderNr" URI:@"" parent:__parent skipNullProperty:YES];
    if(__orderNrItemElement!=nil)
    {
        [__orderNrItemElement setStringValue:self.orderNr];
    }
             
    DDXMLElement* __ssccItemElement=[__request writeElement:sscc type:[NSString class] name:@"sscc" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ssccItemElement!=nil)
    {
        [__ssccItemElement setStringValue:self.sscc];
    }


}
@end
