//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 21-04-2015
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "webServiceResult.h"
#import "checkinItems.h"
#import "order.h"
#import "checkoutItems.h"
#import "insertTrackingItems.h"
#import "getItemsBySSCCResponse.h"
#import "production.h"
#import "getQuantitiesResponse.h"
#import "getOpenOrdersByGLNResponse.h"
#import "item.h"
#import "getItemsByBatchResponse.h"
#import "mediPrepResult.h"
#import "updatePreparedMedications.h"
#import "updatePrescriptions.h"
#import "getLogisticUnitsForProductResponse.h"
#import "getStationsResponse.h"
#import "getPatientsResponse.h"
#import "getPrescriptionsForPatientResponse.h"
#import "getPrescriptionsWithPreparedMedicationsForPatientResponse.h"
#import "savePreparedMedications.h"
#import "getPreparedMedicationsForPatientResponse.h"
#import "DDXML.h"

@class RequestResultHandler;

@protocol SoapServiceResponse < NSObject>
- (void) onSuccess: (id) value methodName:(NSString*)methodName;
- (void) onError: (NSError*) error;
@end


@interface SupplyChainServicePortBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;
@property BOOL EnableLogging;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) createsayHelloWorldFromRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(NSString*) sayHelloWorldFrom:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) sayHelloWorldFromAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) sayHelloWorldFromAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetCheckedInItemsRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(webServiceResult*) getCheckedInItems:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) getCheckedInItemsAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getCheckedInItemsAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) createcheckinItemsRequest:(checkinItems*) checkinItems __request:(RequestResultHandler*) __request;
-(webServiceResult*) checkinItems:(checkinItems*) checkinItems __error:(NSError**) __error;
-(RequestResultHandler*) checkinItemsAsync:(checkinItems*) checkinItems __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) checkinItemsAsync:(checkinItems*) checkinItems __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) createsetOrderRequest:(order*) arg0 arg1:(NSString*) arg1 arg2:(NSString*) arg2 __request:(RequestResultHandler*) __request;
-(NSNumber*) setOrder:(order*) arg0 arg1:(NSString*) arg1 arg2:(NSString*) arg2 __error:(NSError**) __error;
-(RequestResultHandler*) setOrderAsync:(order*) arg0 arg1:(NSString*) arg1 arg2:(NSString*) arg2 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) setOrderAsync:(order*) arg0 arg1:(NSString*) arg1 arg2:(NSString*) arg2 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) createcheckoutItemsRequest:(checkoutItems*) checkoutItems __request:(RequestResultHandler*) __request;
-(webServiceResult*) checkoutItems:(checkoutItems*) checkoutItems __error:(NSError**) __error;
-(RequestResultHandler*) checkoutItemsAsync:(checkoutItems*) checkoutItems __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) checkoutItemsAsync:(checkoutItems*) checkoutItems __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) createinsertTrackingItemsRequest:(insertTrackingItems*) insertTrackingItems __request:(RequestResultHandler*) __request;
-(void) insertTrackingItems:(insertTrackingItems*) insertTrackingItems __error:(NSError**) __error;
-(RequestResultHandler*) insertTrackingItemsAsync:(insertTrackingItems*) insertTrackingItems __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) insertTrackingItemsAsync:(insertTrackingItems*) insertTrackingItems __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetItemsBySSCCRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(getItemsBySSCCResponse*) getItemsBySSCC:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) getItemsBySSCCAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getItemsBySSCCAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) createprocessOrderRequest:(order*) arg0 arg1:(NSString*) arg1 arg2:(NSString*) arg2 __request:(RequestResultHandler*) __request;
-(production*) processOrder:(order*) arg0 arg1:(NSString*) arg1 arg2:(NSString*) arg2 __error:(NSError**) __error;
-(RequestResultHandler*) processOrderAsync:(order*) arg0 arg1:(NSString*) arg1 arg2:(NSString*) arg2 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) processOrderAsync:(order*) arg0 arg1:(NSString*) arg1 arg2:(NSString*) arg2 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetQuantitiesRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(getQuantitiesResponse*) getQuantities:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) getQuantitiesAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getQuantitiesAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetOpenOrdersByGLNRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(getOpenOrdersByGLNResponse*) getOpenOrdersByGLN:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) getOpenOrdersByGLNAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getOpenOrdersByGLNAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetItemByIdentifierRequest:(NSString*) arg0 arg1:(NSString*) arg1 __request:(RequestResultHandler*) __request;
-(item*) getItemByIdentifier:(NSString*) arg0 arg1:(NSString*) arg1 __error:(NSError**) __error;
-(RequestResultHandler*) getItemByIdentifierAsync:(NSString*) arg0 arg1:(NSString*) arg1 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getItemByIdentifierAsync:(NSString*) arg0 arg1:(NSString*) arg1 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetItemsByBatchRequest:(NSString*) arg0 arg1:(NSString*) arg1 arg2:(NSDate*) arg2 __request:(RequestResultHandler*) __request;
-(getItemsByBatchResponse*) getItemsByBatch:(NSString*) arg0 arg1:(NSString*) arg1 arg2:(NSDate*) arg2 __error:(NSError**) __error;
-(RequestResultHandler*) getItemsByBatchAsync:(NSString*) arg0 arg1:(NSString*) arg1 arg2:(NSDate*) arg2 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getItemsByBatchAsync:(NSString*) arg0 arg1:(NSString*) arg1 arg2:(NSDate*) arg2 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetOrderForSSCCRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(NSString*) getOrderForSSCC:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) getOrderForSSCCAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getOrderForSSCCAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) createresetTrackedItemsRequest:(RequestResultHandler*) __request;
-(void) resetTrackedItems:(NSError**) __error;
-(RequestResultHandler*) resetTrackedItemsAsync:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) resetTrackedItemsAsync:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) createupdatePreparedMedicationsRequest:(updatePreparedMedications*) updatePreparedMedications __request:(RequestResultHandler*) __request;
-(mediPrepResult*) updatePreparedMedications:(updatePreparedMedications*) updatePreparedMedications __error:(NSError**) __error;
-(RequestResultHandler*) updatePreparedMedicationsAsync:(updatePreparedMedications*) updatePreparedMedications __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) updatePreparedMedicationsAsync:(updatePreparedMedications*) updatePreparedMedications __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) createupdatePrescriptionsRequest:(updatePrescriptions*) updatePrescriptions __request:(RequestResultHandler*) __request;
-(NSNumber*) updatePrescriptions:(updatePrescriptions*) updatePrescriptions __error:(NSError**) __error;
-(RequestResultHandler*) updatePrescriptionsAsync:(updatePrescriptions*) updatePrescriptions __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) updatePrescriptionsAsync:(updatePrescriptions*) updatePrescriptions __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetDosetForPatientRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(NSString*) getDosetForPatient:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) getDosetForPatientAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getDosetForPatientAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetLogisticUnitsForProductRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(getLogisticUnitsForProductResponse*) getLogisticUnitsForProduct:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) getLogisticUnitsForProductAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getLogisticUnitsForProductAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetPreparedPrescriptionsCountForPatientRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(NSNumber*) getPreparedPrescriptionsCountForPatient:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) getPreparedPrescriptionsCountForPatientAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getPreparedPrescriptionsCountForPatientAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetItemsByGSINRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(webServiceResult*) getItemsByGSIN:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) getItemsByGSINAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getItemsByGSINAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetStationsRequest:(RequestResultHandler*) __request;
-(getStationsResponse*) getStations:(NSError**) __error;
-(RequestResultHandler*) getStationsAsync:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getStationsAsync:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetPatientsRequest:(RequestResultHandler*) __request;
-(getPatientsResponse*) getPatients:(NSError**) __error;
-(RequestResultHandler*) getPatientsAsync:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getPatientsAsync:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetPrescriptionsForPatientRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(getPrescriptionsForPatientResponse*) getPrescriptionsForPatient:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) getPrescriptionsForPatientAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getPrescriptionsForPatientAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetPrescriptionsWithPreparedMedicationsForPatientRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(getPrescriptionsWithPreparedMedicationsForPatientResponse*) getPrescriptionsWithPreparedMedicationsForPatient:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) getPrescriptionsWithPreparedMedicationsForPatientAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getPrescriptionsWithPreparedMedicationsForPatientAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) createsavePreparedMedicationsRequest:(savePreparedMedications*) savePreparedMedications __request:(RequestResultHandler*) __request;
-(NSNumber*) savePreparedMedications:(savePreparedMedications*) savePreparedMedications __error:(NSError**) __error;
-(RequestResultHandler*) savePreparedMedicationsAsync:(savePreparedMedications*) savePreparedMedications __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) savePreparedMedicationsAsync:(savePreparedMedications*) savePreparedMedications __target:(id<SoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetPreparedMedicationsForPatientRequest:(NSString*) arg0 __request:(RequestResultHandler*) __request;
-(getPreparedMedicationsForPatientResponse*) getPreparedMedicationsForPatient:(NSString*) arg0 __error:(NSError**) __error;
-(RequestResultHandler*) getPreparedMedicationsForPatientAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(RequestResultHandler*) getPreparedMedicationsForPatientAsync:(NSString*) arg0 __target:(id<SoapServiceResponse>) __target;
-(RequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(RequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(RequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(RequestResultHandler*) requestMgr callback:(void (^)(RequestResultHandler *)) callback;

@end
