//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 21-04-2015
//
//---------------------------------------------------


#import "trspPrescription.h"
#import "Helper.h"
#import "toDoListPrescriptions.h"


@implementation toDoListPrescriptions
@synthesize scheduldedPrescriptionsEvening;
@synthesize scheduldedPrescriptionsMorning;
@synthesize scheduldedPrescriptionsNight;
@synthesize scheduldedPrescriptionsNoon;

+ (toDoListPrescriptions *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.scheduldedPrescriptionsEvening =[NSMutableArray array];
        self.scheduldedPrescriptionsMorning =[NSMutableArray array];
        self.scheduldedPrescriptionsNight =[NSMutableArray array];
        self.scheduldedPrescriptionsNoon =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"scheduldedPrescriptionsEvening"])
        {
            NSArray* __items=[__node elementsForName:@"scheduldedPrescriptionsEvening"];
            for (DDXMLElement* __item in __items) {
                [self.scheduldedPrescriptionsEvening addObject:(trspPrescription*)[__request createObject:__item type:[trspPrescription class]]];
            }
        }
        if([Helper hasValue:__node name:@"scheduldedPrescriptionsMorning"])
        {
            NSArray* __items=[__node elementsForName:@"scheduldedPrescriptionsMorning"];
            for (DDXMLElement* __item in __items) {
                [self.scheduldedPrescriptionsMorning addObject:(trspPrescription*)[__request createObject:__item type:[trspPrescription class]]];
            }
        }
        if([Helper hasValue:__node name:@"scheduldedPrescriptionsNight"])
        {
            NSArray* __items=[__node elementsForName:@"scheduldedPrescriptionsNight"];
            for (DDXMLElement* __item in __items) {
                [self.scheduldedPrescriptionsNight addObject:(trspPrescription*)[__request createObject:__item type:[trspPrescription class]]];
            }
        }
        if([Helper hasValue:__node name:@"scheduldedPrescriptionsNoon"])
        {
            NSArray* __items=[__node elementsForName:@"scheduldedPrescriptionsNoon"];
            for (DDXMLElement* __item in __items) {
                [self.scheduldedPrescriptionsNoon addObject:(trspPrescription*)[__request createObject:__item type:[trspPrescription class]]];
            }
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
    if(self.scheduldedPrescriptionsEvening!=nil)
    {
        for (trspPrescription* __item in self.scheduldedPrescriptionsEvening) {
            DDXMLElement* __scheduldedPrescriptionsEveningItemElement=[__request writeElement:scheduldedPrescriptionsEvening type:[trspPrescription class] name:@"scheduldedPrescriptionsEvening" URI:@"" parent:__parent skipNullProperty:NO];
            if(__scheduldedPrescriptionsEveningItemElement!=nil)
            {
                [__item serialize:__scheduldedPrescriptionsEveningItemElement __request: __request];
            }
        }
    }
             
    if(self.scheduldedPrescriptionsMorning!=nil)
    {
        for (trspPrescription* __item in self.scheduldedPrescriptionsMorning) {
            DDXMLElement* __scheduldedPrescriptionsMorningItemElement=[__request writeElement:scheduldedPrescriptionsMorning type:[trspPrescription class] name:@"scheduldedPrescriptionsMorning" URI:@"" parent:__parent skipNullProperty:NO];
            if(__scheduldedPrescriptionsMorningItemElement!=nil)
            {
                [__item serialize:__scheduldedPrescriptionsMorningItemElement __request: __request];
            }
        }
    }
             
    if(self.scheduldedPrescriptionsNight!=nil)
    {
        for (trspPrescription* __item in self.scheduldedPrescriptionsNight) {
            DDXMLElement* __scheduldedPrescriptionsNightItemElement=[__request writeElement:scheduldedPrescriptionsNight type:[trspPrescription class] name:@"scheduldedPrescriptionsNight" URI:@"" parent:__parent skipNullProperty:NO];
            if(__scheduldedPrescriptionsNightItemElement!=nil)
            {
                [__item serialize:__scheduldedPrescriptionsNightItemElement __request: __request];
            }
        }
    }
             
    if(self.scheduldedPrescriptionsNoon!=nil)
    {
        for (trspPrescription* __item in self.scheduldedPrescriptionsNoon) {
            DDXMLElement* __scheduldedPrescriptionsNoonItemElement=[__request writeElement:scheduldedPrescriptionsNoon type:[trspPrescription class] name:@"scheduldedPrescriptionsNoon" URI:@"" parent:__parent skipNullProperty:NO];
            if(__scheduldedPrescriptionsNoonItemElement!=nil)
            {
                [__item serialize:__scheduldedPrescriptionsNoonItemElement __request: __request];
            }
        }
    }


}
@end
