//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 16-04-2015
//
//---------------------------------------------------


#import "trspPreparedMedication.h"
#import "Helper.h"
#import "trspPrescription.h"


@implementation trspPrescription
@synthesize createdByStaffGLN;
@synthesize dateCreated;
@synthesize description;
@synthesize firstName;
@synthesize medications;
@synthesize name;
@synthesize patientPolypointID;
@synthesize polypointID;
@synthesize position;
@synthesize routeOfAdministration;
@synthesize schedule;

+ (trspPrescription *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.medications =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"createdByStaffGLN" index:0])
        {
            self.createdByStaffGLN = [[Helper getNode:__node name:@"createdByStaffGLN" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"dateCreated" index:0])
        {
            self.dateCreated = [[Helper getNode:__node name:@"dateCreated" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"description" index:0])
        {
            self.description = [[Helper getNode:__node name:@"description" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"firstName" index:0])
        {
            self.firstName = [[Helper getNode:__node name:@"firstName" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"medications"])
        {
            NSArray* __items=[__node elementsForName:@"medications"];
            for (DDXMLElement* __item in __items) {
                [self.medications addObject:(trspPreparedMedication*)[__request createObject:__item type:[trspPreparedMedication class]]];
            }
        }
        if([Helper hasValue:__node name:@"name" index:0])
        {
            self.name = [[Helper getNode:__node name:@"name" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"patientPolypointID" index:0])
        {
            self.patientPolypointID = [[Helper getNode:__node name:@"patientPolypointID" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"polypointID" index:0])
        {
            self.polypointID = [[Helper getNode:__node name:@"polypointID" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"position" index:0])
        {
            self.position = [[Helper getNode:__node name:@"position" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"routeOfAdministration" index:0])
        {
            self.routeOfAdministration = [[Helper getNode:__node name:@"routeOfAdministration" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"schedule" index:0])
        {
            self.schedule = [[Helper getNode:__node name:@"schedule" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
    DDXMLElement* __createdByStaffGLNItemElement=[__request writeElement:createdByStaffGLN type:[NSString class] name:@"createdByStaffGLN" URI:@"" parent:__parent skipNullProperty:YES];
    if(__createdByStaffGLNItemElement!=nil)
    {
        [__createdByStaffGLNItemElement setStringValue:self.createdByStaffGLN];
    }
             
    DDXMLElement* __dateCreatedItemElement=[__request writeElement:dateCreated type:[NSString class] name:@"dateCreated" URI:@"" parent:__parent skipNullProperty:YES];
    if(__dateCreatedItemElement!=nil)
    {
        [__dateCreatedItemElement setStringValue:self.dateCreated];
    }
             
    DDXMLElement* __descriptionItemElement=[__request writeElement:description type:[NSString class] name:@"description" URI:@"" parent:__parent skipNullProperty:YES];
    if(__descriptionItemElement!=nil)
    {
        [__descriptionItemElement setStringValue:self.description];
    }
             
    DDXMLElement* __firstNameItemElement=[__request writeElement:firstName type:[NSString class] name:@"firstName" URI:@"" parent:__parent skipNullProperty:YES];
    if(__firstNameItemElement!=nil)
    {
        [__firstNameItemElement setStringValue:self.firstName];
    }
             
    if(self.medications!=nil)
    {
        for (trspPreparedMedication* __item in self.medications) {
            DDXMLElement* __medicationsItemElement=[__request writeElement:medications type:[trspPreparedMedication class] name:@"medications" URI:@"" parent:__parent skipNullProperty:NO];
            if(__medicationsItemElement!=nil)
            {
                [__item serialize:__medicationsItemElement __request: __request];
            }
        }
    }
             
    DDXMLElement* __nameItemElement=[__request writeElement:name type:[NSString class] name:@"name" URI:@"" parent:__parent skipNullProperty:YES];
    if(__nameItemElement!=nil)
    {
        [__nameItemElement setStringValue:self.name];
    }
             
    DDXMLElement* __patientPolypointIDItemElement=[__request writeElement:patientPolypointID type:[NSString class] name:@"patientPolypointID" URI:@"" parent:__parent skipNullProperty:YES];
    if(__patientPolypointIDItemElement!=nil)
    {
        [__patientPolypointIDItemElement setStringValue:self.patientPolypointID];
    }
             
    DDXMLElement* __polypointIDItemElement=[__request writeElement:polypointID type:[NSString class] name:@"polypointID" URI:@"" parent:__parent skipNullProperty:YES];
    if(__polypointIDItemElement!=nil)
    {
        [__polypointIDItemElement setStringValue:self.polypointID];
    }
             
    DDXMLElement* __positionItemElement=[__request writeElement:position type:[NSString class] name:@"position" URI:@"" parent:__parent skipNullProperty:YES];
    if(__positionItemElement!=nil)
    {
        [__positionItemElement setStringValue:self.position];
    }
             
    DDXMLElement* __routeOfAdministrationItemElement=[__request writeElement:routeOfAdministration type:[NSString class] name:@"routeOfAdministration" URI:@"" parent:__parent skipNullProperty:YES];
    if(__routeOfAdministrationItemElement!=nil)
    {
        [__routeOfAdministrationItemElement setStringValue:self.routeOfAdministration];
    }
             
    DDXMLElement* __scheduleItemElement=[__request writeElement:schedule type:[NSString class] name:@"schedule" URI:@"" parent:__parent skipNullProperty:YES];
    if(__scheduleItemElement!=nil)
    {
        [__scheduleItemElement setStringValue:self.schedule];
    }


}
@end
