//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 16-04-2015
//
//---------------------------------------------------


#import "Helper.h"
#import "trspMedication.h"


@implementation trspMedication
@synthesize applicationScheme;
@synthesize description;
@synthesize dosage;
@synthesize dosageUnit;
@synthesize gtin;
@synthesize name;

+ (trspMedication *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"applicationScheme" index:0])
        {
            self.applicationScheme = [[Helper getNode:__node name:@"applicationScheme" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"description" index:0])
        {
            self.description = [[Helper getNode:__node name:@"description" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"dosage" index:0])
        {
            self.dosage = [[Helper getNode:__node name:@"dosage" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"dosageUnit" index:0])
        {
            self.dosageUnit = [[Helper getNode:__node name:@"dosageUnit" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"gtin" index:0])
        {
            self.gtin = [[Helper getNode:__node name:@"gtin" index:0] stringValue];
        }
        if([Helper hasValue:__node name:@"name" index:0])
        {
            self.name = [[Helper getNode:__node name:@"name" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
    DDXMLElement* __applicationSchemeItemElement=[__request writeElement:applicationScheme type:[NSString class] name:@"applicationScheme" URI:@"" parent:__parent skipNullProperty:YES];
    if(__applicationSchemeItemElement!=nil)
    {
        [__applicationSchemeItemElement setStringValue:self.applicationScheme];
    }
             
    DDXMLElement* __descriptionItemElement=[__request writeElement:description type:[NSString class] name:@"description" URI:@"" parent:__parent skipNullProperty:YES];
    if(__descriptionItemElement!=nil)
    {
        [__descriptionItemElement setStringValue:self.description];
    }
             
    DDXMLElement* __dosageItemElement=[__request writeElement:dosage type:[NSString class] name:@"dosage" URI:@"" parent:__parent skipNullProperty:YES];
    if(__dosageItemElement!=nil)
    {
        [__dosageItemElement setStringValue:self.dosage];
    }
             
    DDXMLElement* __dosageUnitItemElement=[__request writeElement:dosageUnit type:[NSString class] name:@"dosageUnit" URI:@"" parent:__parent skipNullProperty:YES];
    if(__dosageUnitItemElement!=nil)
    {
        [__dosageUnitItemElement setStringValue:self.dosageUnit];
    }
             
    DDXMLElement* __gtinItemElement=[__request writeElement:gtin type:[NSString class] name:@"gtin" URI:@"" parent:__parent skipNullProperty:YES];
    if(__gtinItemElement!=nil)
    {
        [__gtinItemElement setStringValue:self.gtin];
    }
             
    DDXMLElement* __nameItemElement=[__request writeElement:name type:[NSString class] name:@"name" URI:@"" parent:__parent skipNullProperty:YES];
    if(__nameItemElement!=nil)
    {
        [__nameItemElement setStringValue:self.name];
    }


}
@end
