//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 23-04-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class trspPreparedMedication;
@class prescriptionState;
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface trspPrescription : NSObject <ISerializableObject>


@property (retain,nonatomic,getter=getCreatedByStaffGLN) NSString* createdByStaffGLN;

@property (retain,nonatomic,getter=getDateCreated) NSString* dateCreated;

@property (retain,nonatomic,getter=getDescription) NSString* description;

@property (retain,nonatomic,getter=getFirstName) NSString* firstName;

@property (retain,nonatomic,getter=getMedications) NSMutableArray* medications;

@property (retain,nonatomic,getter=getMedicationsEvening) NSMutableArray* medicationsEvening;

@property (retain,nonatomic,getter=getMedicationsMorning) NSMutableArray* medicationsMorning;

@property (retain,nonatomic,getter=getMedicationsNight) NSMutableArray* medicationsNight;

@property (retain,nonatomic,getter=getMedicationsNoon) NSMutableArray* medicationsNoon;

@property (retain,nonatomic,getter=getName) NSString* name;

@property (retain,nonatomic,getter=getNotes) NSString* notes;

@property (retain,nonatomic,getter=getPatientPolypointID) NSString* patientPolypointID;

@property (retain,nonatomic,getter=getPolypointID) NSString* polypointID;

@property (retain,nonatomic,getter=getPosition) NSString* position;

@property (retain,nonatomic,getter=getPrescriptionState) prescriptionState* prescriptionState;

@property (retain,nonatomic,getter=getRouteOfAdministration) NSString* routeOfAdministration;

@property (retain,nonatomic,getter=getSchedule) NSString* schedule;

@property (retain,nonatomic,getter=getVaildUntil) NSString* vaildUntil;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(trspPrescription*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end