//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 16-04-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "RequestResultHandler.h"
#import "DDXML.h"



@interface trspMedication : NSObject <ISerializableObject>


@property (retain,nonatomic,getter=getApplicationScheme) NSString* applicationScheme;

@property (retain,nonatomic,getter=getDescription) NSString* description;

@property (retain,nonatomic,getter=getDosage) NSString* dosage;

@property (retain,nonatomic,getter=getDosageUnit) NSString* dosageUnit;

@property (retain,nonatomic,getter=getGtin) NSString* gtin;

@property (retain,nonatomic,getter=getName) NSString* name;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(trspMedication*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end