//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 16-04-2015
//
//---------------------------------------------------


#import "trspPreparedMedication.h"
#import "medicationState.h"
#import "Helper.h"
#import "updatePreparedMedications.h"


@implementation updatePreparedMedications
@synthesize arg0;
@synthesize arg1;

+ (updatePreparedMedications *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.arg0 =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"arg0"])
        {
            NSArray* __items=[__node elementsForName:@"arg0"];
            for (DDXMLElement* __item in __items) {
                [self.arg0 addObject:(trspPreparedMedication*)[__request createObject:__item type:[trspPreparedMedication class]]];
            }
        }
        if([Helper hasValue:__node name:@"arg1" index:0])
        {
            self.arg1 = (medicationState*)[medicationState createWithXml:[Helper getNode:__node name:@"arg1" index:0]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
    if(self.arg0!=nil)
    {
        for (trspPreparedMedication* __item in self.arg0) {
            DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[trspPreparedMedication class] name:@"arg0" URI:@"" parent:__parent skipNullProperty:NO];
            if(__arg0ItemElement!=nil)
            {
                [__item serialize:__arg0ItemElement __request: __request];
            }
        }
    }
             
    DDXMLElement* __arg1ItemElement=[__request writeElement:arg1 type:[medicationState class] name:@"arg1" URI:@"" parent:__parent skipNullProperty:YES];
    if(__arg1ItemElement!=nil)
    {
        [self.arg1 serialize:__arg1ItemElement];
    }


}
@end
