//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.4
//
// Created by Quasar Development at 16-04-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class trspPreparedMedication;
@class medicationState;
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface updatePreparedMedications : NSObject <ISerializableObject>


@property (retain,nonatomic,getter=getArg0) NSMutableArray* arg0;

@property (retain,nonatomic,getter=getArg1) medicationState* arg1;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(updatePreparedMedications*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end